### ISSUE TITLE
Missing errors for enum shapes without members

### ISSUE THREAD

**Issue by milesziemer** [awslabs/smithy-language-server#81]
Take the following model:
```
$version: "2"

namespace smithy.example

enum Foo {}
```
Building this model fails with something like:
```
ERROR: smithy.example#Foo (Model)
     = enum must have at least one entry
```
But the language server does not give any highlighting or underlying indicating that enums must have at least one entry.

**Comment by daddykotex** [comment]
I found that the issue originates from smithy-model. This is because we're missing the location for the SyntheticEnumTrait that's created and where the validation happen. Because the location is not there,  the language server can bind the validation error to a `Diagnostic` on a file.

Tested with a local publish:

![Screen Shot 2023-01-12 at 10 49 38](https://user-images.githubusercontent.com/5230460/212119809-20575c7e-1668-4333-b095-292c2b1e9e8f.png)
